#!/usr/bin/env bun
/**
 * Generate a typed TypeScript client from registered collections.
 *
 *   bun run generate:client
 *
 * Output: src/client/generated.ts (build-time only — not imported by server)
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { getRegisteredCollections } from '../src/schema/registry.js'
import type { CollectionSchema, FieldSchema } from '../src/schema/types.js'

import '../collections.js'

function fieldTsType(field: FieldSchema): string {
  switch (field.type) {
    case 'string':
    case 'text':
    case 'reference':
      return 'string'
    case 'integer':
    case 'real':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'date':
      return 'string | Date | number'
    case 'json':
      return 'unknown'
    case 'vector':
      return 'number[]'
    default:
      return 'unknown'
  }
}

function genCollectionTypes(collection: CollectionSchema): string {
  const fields = Object.entries(collection.fields)
    .map(([name, field]) => {
      const optional = !field.required
      return `  ${name}${optional ? '?' : ''}: ${fieldTsType(field)}`
    })
    .join('\n')

  const createFields = Object.entries(collection.fields)
    .map(([name, field]) => {
      const optional = !field.required || field.default !== undefined
      // owner fields are server-set
      if (
        collection.access?.ownerField === name &&
        collection.access?.create === 'owner'
      ) {
        return `  ${name}?: ${fieldTsType(field)}`
      }
      return `  ${name}${optional ? '?' : ''}: ${fieldTsType(field)}`
    })
    .join('\n')

  const updateFields = Object.entries(collection.fields)
    .map(([name, field]) => `  ${name}?: ${fieldTsType(field)} | null`)
    .join('\n')

  const pascal = collection.name
    .split(/[_-]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')

  return `
export interface ${pascal} {
  id: string
  createdAt: number
  updatedAt: number
${fields}
}

export type ${pascal}Create = {
${createFields}
}

export type ${pascal}Update = {
${updateFields}
}
`
}

function main() {
  const collections = getRegisteredCollections().filter(
    (c) => c.name !== 'user' && c.name !== 'users',
  )

  const typeBlocks = collections.map(genCollectionTypes).join('\n')

  const collectionMethods = collections
    .map((c) => {
      const pascal = c.name
        .split(/[_-]/)
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
        .join('')
      return `  ${c.name}: CollectionClient<${pascal}, ${pascal}Create, ${pascal}Update>`
    })
    .join('\n')

  const initCollections = collections
    .map(
      (c) =>
        `    this.${c.name} = createCollectionClient(this, '${c.name}')`,
    )
    .join('\n')

  const source = `/* eslint-disable */
/**
 * AUTO-GENERATED by \`bun run generate:client\` — do not edit by hand.
 * Generated at ${new Date().toISOString()}
 */
${typeBlocks}

export interface ListMeta {
  page: number
  perPage: number
  total: number
  totalPages: number
}

export interface ListResult<T> {
  data: T[]
  meta: ListMeta
}

export interface ApiErrorBody {
  error: { code: string; message: string; details?: unknown }
}

export class BaseClientError extends Error {
  constructor(
    public status: number,
    public body: ApiErrorBody,
  ) {
    super(body.error?.message || \`Request failed (\${status})\`)
    this.name = 'BaseClientError'
  }
}

export interface BaseClientOptions {
  baseUrl: string
  /** Cookie header value (e.g. from document.cookie or set-cookie join) */
  cookie?: string
  /** Bearer / session token if not using cookies */
  headers?: Record<string, string>
  fetch?: typeof fetch
}

type CollectionClient<T, C, U> = {
  list(params?: {
    filter?: Record<string, string>
    sort?: string
    page?: number
    perPage?: number
  }): Promise<ListResult<T>>
  get(id: string): Promise<T>
  create(data: C): Promise<T>
  update(id: string, data: U): Promise<T>
  delete(id: string, opts?: { hard?: boolean }): Promise<{ id: string; deleted: boolean; soft: boolean }>
}

function createCollectionClient<T, C, U>(
  client: BaseClient,
  name: string,
): CollectionClient<T, C, U> {
  const base = () => \`\${client.baseUrl}/api/collections/\${name}\`
  return {
    async list(params) {
      const qs = new URLSearchParams()
      if (params?.filter) qs.set('filter', JSON.stringify(params.filter))
      if (params?.sort) qs.set('sort', params.sort)
      if (params?.page) qs.set('page', String(params.page))
      if (params?.perPage) qs.set('perPage', String(params.perPage))
      const q = qs.toString()
      return client.request(q ? \`\${base()}?\${q}\` : base())
    },
    async get(id) {
      const res = await client.request<{ data: T }>(\`\${base()}/\${id}\`)
      return res.data
    },
    async create(data) {
      const res = await client.request<{ data: T }>(base(), {
        method: 'POST',
        body: JSON.stringify(data),
      })
      return res.data
    },
    async update(id, data) {
      const res = await client.request<{ data: T }>(\`\${base()}/\${id}\`, {
        method: 'PATCH',
        body: JSON.stringify(data),
      })
      return res.data
    },
    async delete(id, opts) {
      const url = opts?.hard ? \`\${base()}/\${id}?hard=true\` : \`\${base()}/\${id}\`
      const res = await client.request<{ data: { id: string; deleted: boolean; soft: boolean } }>(url, {
        method: 'DELETE',
      })
      return res.data
    },
  }
}

export class BaseClient {
  readonly baseUrl: string
  private cookie?: string
  private extraHeaders: Record<string, string>
  private fetchImpl: typeof fetch

${collectionMethods}

  constructor(options: BaseClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\\/$/, '')
    this.cookie = options.cookie
    this.extraHeaders = options.headers || {}
    this.fetchImpl = options.fetch || globalThis.fetch.bind(globalThis)
${initCollections}
  }

  setCookie(cookie: string) {
    this.cookie = cookie
  }

  async request<T = unknown>(url: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers)
    if (!headers.has('Content-Type') && init.body) {
      headers.set('Content-Type', 'application/json')
    }
    for (const [k, v] of Object.entries(this.extraHeaders)) {
      headers.set(k, v)
    }
    if (this.cookie) {
      headers.set('Cookie', this.cookie)
    }

    const res = await this.fetchImpl(url, { ...init, headers })
    const json = await res.json().catch(() => ({}))
    if (!res.ok) {
      throw new BaseClientError(res.status, json as ApiErrorBody)
    }
    return json as T
  }

  async signUp(body: { email: string; password: string; name: string }) {
    return this.request(\`\${this.baseUrl}/api/auth/sign-up/email\`, {
      method: 'POST',
      body: JSON.stringify(body),
    })
  }

  async signIn(body: { email: string; password: string }) {
    const res = await this.fetchImpl(\`\${this.baseUrl}/api/auth/sign-in/email\`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...this.extraHeaders,
        ...(this.cookie ? { Cookie: this.cookie } : {}),
      },
      body: JSON.stringify(body),
    })
    const anyHeaders = res.headers as Headers & { getSetCookie?: () => string[] }
    const setCookie =
      anyHeaders.getSetCookie?.() ||
      (res.headers.get('set-cookie') ? [res.headers.get('set-cookie')!] : [])
    if (setCookie.length) {
      this.cookie = setCookie.map((c) => c.split(';')[0]).join('; ')
    }
    const json = await res.json()
    if (!res.ok) {
      throw new BaseClientError(res.status, json as ApiErrorBody)
    }
    return json
  }

  async me() {
    return this.request(\`\${this.baseUrl}/api/auth/me\`)
  }

  async uploadFile(file: File | Blob, filename?: string) {
    const form = new FormData()
    if (file instanceof File) {
      form.append('file', file)
    } else {
      form.append('file', file, filename || 'upload.bin')
    }
    const headers = new Headers(this.extraHeaders)
    if (this.cookie) headers.set('Cookie', this.cookie)
    const res = await this.fetchImpl(\`\${this.baseUrl}/api/files\`, {
      method: 'POST',
      headers,
      body: form,
    })
    const json = await res.json()
    if (!res.ok) throw new BaseClientError(res.status, json as ApiErrorBody)
    return json
  }
}
`

  const outPath = join(import.meta.dir, '../src/client/generated.ts')
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, source)
  console.log(`✅ Generated client → ${outPath}`)
  console.log(`   Collections: ${collections.map((c) => c.name).join(', ') || '(none)'}`)
}

main()
