/* eslint-disable */
/**
 * AUTO-GENERATED by `bun run generate:client` — do not edit by hand.
 * Generated at 2026-07-28T17:55:47.600Z
 */

export interface Posts {
  id: string
  createdAt: number
  updatedAt: number
  title: string
  content?: string
  slug?: string
  published?: boolean
  viewCount?: number
  authorId: string
}

export type PostsCreate = {
  title: string
  content?: string
  slug?: string
  published?: boolean
  viewCount?: number
  authorId?: string
}

export type PostsUpdate = {
  title?: string | null
  content?: string | null
  slug?: string | null
  published?: boolean | null
  viewCount?: number | null
  authorId?: string | null
}


export interface ListMeta {
  page: number
  perPage: number
  total: number
  totalPages: number
}

export interface ListResult<T> {
  data: T[]
  meta: ListMeta
}

export interface ApiErrorBody {
  error: { code: string; message: string; details?: unknown }
}

export class BaseClientError extends Error {
  constructor(
    public status: number,
    public body: ApiErrorBody,
  ) {
    super(body.error?.message || `Request failed (${status})`)
    this.name = 'BaseClientError'
  }
}

export interface ChangeEvent<T = Record<string, unknown>> {
  id: string
  collection: string
  action: 'create' | 'update' | 'delete'
  recordId: string
  record: T
  ts: number
}

export interface Subscription {
  close(): void
}

export interface SubscribeOptions {
  /** Called on connection errors; return false to stop reconnecting */
  onError?: (err: unknown) => void | boolean
  /** Initial Last-Event-ID for replay */
  lastEventId?: string
  /** Reconnect with exponential backoff (default true) */
  reconnect?: boolean
}

export interface BaseClientOptions {
  baseUrl: string
  /** Cookie header value (e.g. from document.cookie or set-cookie join) */
  cookie?: string
  /** Bearer / session token if not using cookies */
  headers?: Record<string, string>
  fetch?: typeof fetch
}

type CollectionClient<T, C, U> = {
  list(params?: {
    filter?: Record<string, string>
    sort?: string
    page?: number
    perPage?: number
  }): Promise<ListResult<T>>
  get(id: string): Promise<T>
  create(data: C): Promise<T>
  update(id: string, data: U): Promise<T>
  delete(id: string, opts?: { hard?: boolean }): Promise<{ id: string; deleted: boolean; soft: boolean }>
  subscribe(
    handler: (event: ChangeEvent<T>) => void,
    opts?: SubscribeOptions,
  ): Subscription
}

function parseSseFrames(buffer: string): { frames: Array<{ event?: string; data?: string; id?: string }>; rest: string } {
  const frames: Array<{ event?: string; data?: string; id?: string }> = []
  const parts = buffer.split('\n\n')
  const rest = parts.pop() ?? ''
  for (const part of parts) {
    if (!part.trim()) continue
    const frame: { event?: string; data?: string; id?: string } = {}
    const dataLines: string[] = []
    for (const line of part.split('\n')) {
      if (line.startsWith(':')) continue
      if (line.startsWith('event:')) frame.event = line.slice(6).trim()
      else if (line.startsWith('data:')) dataLines.push(line.slice(5).trimStart())
      else if (line.startsWith('id:')) frame.id = line.slice(3).trim()
    }
    if (dataLines.length) frame.data = dataLines.join('\n')
    frames.push(frame)
  }
  return { frames, rest }
}

function createCollectionClient<T, C, U>(
  client: BaseClient,
  name: string,
): CollectionClient<T, C, U> {
  const base = () => `${client.baseUrl}/api/collections/${name}`
  return {
    async list(params) {
      const qs = new URLSearchParams()
      if (params?.filter) qs.set('filter', JSON.stringify(params.filter))
      if (params?.sort) qs.set('sort', params.sort)
      if (params?.page) qs.set('page', String(params.page))
      if (params?.perPage) qs.set('perPage', String(params.perPage))
      const q = qs.toString()
      return client.request(q ? `${base()}?${q}` : base())
    },
    async get(id) {
      const res = await client.request<{ data: T }>(`${base()}/${id}`)
      return res.data
    },
    async create(data) {
      const res = await client.request<{ data: T }>(base(), {
        method: 'POST',
        body: JSON.stringify(data),
      })
      return res.data
    },
    async update(id, data) {
      const res = await client.request<{ data: T }>(`${base()}/${id}`, {
        method: 'PATCH',
        body: JSON.stringify(data),
      })
      return res.data
    },
    async delete(id, opts) {
      const url = opts?.hard ? `${base()}/${id}?hard=true` : `${base()}/${id}`
      const res = await client.request<{ data: { id: string; deleted: boolean; soft: boolean } }>(url, {
        method: 'DELETE',
      })
      return res.data
    },
    subscribe(handler, opts) {
      return client.subscribeMany(
        [name],
        (event) => handler(event as ChangeEvent<T>),
        opts,
      )
    },
  }
}

export class BaseClient {
  readonly baseUrl: string
  private cookie?: string
  private extraHeaders: Record<string, string>
  private fetchImpl: typeof fetch

  posts: CollectionClient<Posts, PostsCreate, PostsUpdate>

  constructor(options: BaseClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/$/, '')
    this.cookie = options.cookie
    this.extraHeaders = options.headers || {}
    this.fetchImpl = options.fetch || globalThis.fetch.bind(globalThis)
    this.posts = createCollectionClient(this, 'posts')
  }

  setCookie(cookie: string) {
    this.cookie = cookie
  }

  async request<T = unknown>(url: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers)
    if (!headers.has('Content-Type') && init.body) {
      headers.set('Content-Type', 'application/json')
    }
    for (const [k, v] of Object.entries(this.extraHeaders)) {
      headers.set(k, v)
    }
    if (this.cookie) {
      headers.set('Cookie', this.cookie)
    }

    const res = await this.fetchImpl(url, { ...init, headers })
    const json = await res.json().catch(() => ({}))
    if (!res.ok) {
      throw new BaseClientError(res.status, json as ApiErrorBody)
    }
    return json as T
  }

  /**
   * Subscribe to change events for one or more collections via SSE
   * (fetch + ReadableStream — supports Cookie / Authorization headers).
   */
  subscribeMany(
    collections: string[],
    handler: (event: ChangeEvent) => void,
    opts?: SubscribeOptions,
  ): Subscription {
    const controller = new AbortController()
    let closed = false
    let lastEventId = opts?.lastEventId
    let attempt = 0
    const shouldReconnect = opts?.reconnect !== false

    const run = async () => {
      while (!closed) {
        try {
          const qs = new URLSearchParams()
          qs.set('collections', collections.join(','))
          if (lastEventId) qs.set('lastEventId', lastEventId)

          const headers = new Headers(this.extraHeaders)
          headers.set('Accept', 'text/event-stream')
          if (this.cookie) headers.set('Cookie', this.cookie)
          if (lastEventId) headers.set('Last-Event-ID', lastEventId)

          const res = await this.fetchImpl(
            `${this.baseUrl}/api/realtime?${qs.toString()}`,
            { headers, signal: controller.signal },
          )

          if (!res.ok) {
            const json = await res.json().catch(() => ({}))
            throw new BaseClientError(res.status, json as ApiErrorBody)
          }

          if (!res.body) {
            throw new Error('Realtime response has no body')
          }

          attempt = 0
          const reader = res.body.getReader()
          const decoder = new TextDecoder()
          let buffer = ''

          while (!closed) {
            const { done, value } = await reader.read()
            if (done) break
            buffer += decoder.decode(value, { stream: true })
            const { frames, rest } = parseSseFrames(buffer)
            buffer = rest
            for (const frame of frames) {
              if (frame.id) lastEventId = frame.id
              if (frame.event === 'change' && frame.data) {
                try {
                  handler(JSON.parse(frame.data) as ChangeEvent)
                } catch {
                  // ignore malformed payloads
                }
              }
            }
          }
        } catch (err) {
          if (closed || controller.signal.aborted) break
          const cont = opts?.onError?.(err)
          if (cont === false || !shouldReconnect) break
          attempt += 1
          const delay = Math.min(30_000, 500 * 2 ** Math.min(attempt, 5))
          await new Promise((r) => setTimeout(r, delay))
          continue
        }

        if (closed || !shouldReconnect) break
        attempt += 1
        const delay = Math.min(30_000, 500 * 2 ** Math.min(attempt, 5))
        await new Promise((r) => setTimeout(r, delay))
      }
    }

    void run()

    return {
      close() {
        closed = true
        controller.abort()
      },
    }
  }

  async signUp(body: { email: string; password: string; name: string }) {
    return this.request(`${this.baseUrl}/api/auth/sign-up/email`, {
      method: 'POST',
      body: JSON.stringify(body),
    })
  }

  async signIn(body: { email: string; password: string }) {
    const res = await this.fetchImpl(`${this.baseUrl}/api/auth/sign-in/email`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...this.extraHeaders,
        ...(this.cookie ? { Cookie: this.cookie } : {}),
      },
      body: JSON.stringify(body),
    })
    const anyHeaders = res.headers as Headers & { getSetCookie?: () => string[] }
    const setCookie =
      anyHeaders.getSetCookie?.() ||
      (res.headers.get('set-cookie') ? [res.headers.get('set-cookie')!] : [])
    if (setCookie.length) {
      this.cookie = setCookie.map((c) => c.split(';')[0]).join('; ')
    }
    const json = await res.json()
    if (!res.ok) {
      throw new BaseClientError(res.status, json as ApiErrorBody)
    }
    return json
  }

  async me() {
    return this.request(`${this.baseUrl}/api/auth/me`)
  }

  async uploadFile(file: File | Blob, filename?: string) {
    const form = new FormData()
    if (file instanceof File) {
      form.append('file', file)
    } else {
      form.append('file', file, filename || 'upload.bin')
    }
    const headers = new Headers(this.extraHeaders)
    if (this.cookie) headers.set('Cookie', this.cookie)
    const res = await this.fetchImpl(`${this.baseUrl}/api/files`, {
      method: 'POST',
      headers,
      body: form,
    })
    const json = await res.json()
    if (!res.ok) throw new BaseClientError(res.status, json as ApiErrorBody)
    return json
  }
}
